### ISSUE TITLE
Could you provide the Video or water-level/data?

### ISSUE THREAD

**Issue by zhangchenyu1023** [khoaLearnToCode/water-level#1]
My email is 1142593831@qq.com

**Comment by khoapham2801** [comment]
Sorry for my late reply. 
I can't provide you the video because of privacy problems. Thank you for your interest.

**Comment by zhangchenyu1023** [comment]
So could you provide the picture such as "/data/frames/vid1/frame115200.jpg" "/data/frames/vid2/frame19.jpg", maybe It won't invade your privacy.
